-- ============================================================
-- Sharpet — 02_seed_domains.sql
-- Reference data: quiz domains and their EN/DE/CS names.
-- Idempotent: safe to re-run.
-- ============================================================

insert into public.domains (id, color) values
  (1, '#4FD1FF'),
  (2, '#FF5D73'),
  (3, '#C4F135'),
  (4, '#FFB84F'),
  (5, '#B98CFF'),
  (6, '#4FFFB0'),
  (7, '#FF4FD1'),
  (8, '#FFE14F'),
  (9, '#4FD1FF'),
  (10, '#FF5D73'),
  (11, '#C4F135'),
  (12, '#FFB84F'),
  (13, '#B98CFF'),
  (14, '#4FFFB0'),
  (15, '#FF4FD1'),
  (16, '#FFE14F'),
  (17, '#4FD1FF')
on conflict (id) do nothing;
select setval('public.domains_id_seq', 17);

insert into public.domain_translations (domain_id, language_code, name) values
  (1,'en','Pharmacy/Medicine'),
  (1,'de','Pharmazie/Medizin'),
  (1,'cs','Farmacie/Medicína'),
  (2,'en','Geography'),
  (2,'de','Geografie'),
  (2,'cs','Zeměpis'),
  (3,'en','World Politics'),
  (3,'de','Weltpolitik'),
  (3,'cs','Světová politika'),
  (4,'en','History'),
  (4,'de','Geschichte'),
  (4,'cs','Historie'),
  (5,'en','Sports'),
  (5,'de','Sport'),
  (5,'cs','Sport'),
  (6,'en','Science & Physics'),
  (6,'de','Wissenschaft & Physik'),
  (6,'cs','Věda a fyzika'),
  (7,'en','Biology & Human Body'),
  (7,'de','Biologie & menschlicher Körper'),
  (7,'cs','Biologie a lidské tělo'),
  (8,'en','Literature'),
  (8,'de','Literatur'),
  (8,'cs','Literatura'),
  (9,'en','Art & Music'),
  (9,'de','Kunst & Musik'),
  (9,'cs','Umění a hudba'),
  (10,'en','Technology & Computing'),
  (10,'de','Technologie & Informatik'),
  (10,'cs','Technologie a výpočetní technika'),
  (11,'en','EU'),
  (11,'de','EU'),
  (11,'cs','EU'),
  (12,'en','Mythology & Religion'),
  (12,'de','Mythologie & Religion'),
  (12,'cs','Mytologie a náboženství'),
  (13,'en','Food & Drink'),
  (13,'de','Essen & Trinken'),
  (13,'cs','Jídlo a pití'),
  (14,'en','Space & Astronomy'),
  (14,'de','Weltraum & Astronomie'),
  (14,'cs','Vesmír a astronomie'),
  (15,'en','General Culture/Miscellaneous'),
  (15,'de','Allgemeinwissen'),
  (15,'cs','Všeobecný přehled'),
  (16,'en','Economics'),
  (16,'de','Wirtschaft'),
  (16,'cs','Ekonomie'),
  (17,'en','Nature/Environment'),
  (17,'de','Natur & Umwelt'),
  (17,'cs','Příroda a životní prostředí')
on conflict (domain_id, language_code) do nothing;
